export const categoryIds = [
  "ai",
  "corporate",
  "startup",
  "enterprise",
  "openSource",
  "localAi",
  "homelab",
  "consulting",
  "founderLinkedIn",
  "research",
  "web3",
  "appleSilicon",
  "archLinux",
  "climateTech",
] as const;

export type CategoryId = (typeof categoryIds)[number];

export type BuzzwordCategory = {
  id: CategoryId;
  label: string;
  classification: string;
  guidance: string;
  vocabulary: readonly string[];
};

export const categories: Record<CategoryId, BuzzwordCategory> = {
  ai: {
    id: "ai",
    label: "AI",
    classification: "AI LARP",
    guidance: "Frame ordinary behavior as model orchestration, reasoning, inference, and intelligence layers.",
    vocabulary: [
      "agentic",
      "multimodal",
      "reasoning layer",
      "intelligence substrate",
      "orchestration",
      "open-weight",
      "embeddings",
      "inference",
      "foundation model",
      "semantic",
      "cognitive architecture",
      "alignment",
    ],
  },
  corporate: {
    id: "corporate",
    label: "Corporate",
    classification: "Corporate LARP",
    guidance: "Sound like a slide deck that replaced accountability with alignment rituals.",
    vocabulary: [
      "circle back",
      "take this offline",
      "boil the ocean",
      "double-click",
      "socialise",
      "align stakeholders",
      "move the needle",
      "operationalise",
      "strategic workstream",
      "north star",
      "synergy",
      "value creation",
    ],
  },
  startup: {
    id: "startup",
    label: "Startup",
    classification: "Founder LARP",
    guidance: "Make the sentence sound venture-scale, category-defining, and suspiciously close to a pitch deck.",
    vocabulary: [
      "B2B SaaS",
      "category-defining",
      "venture-scale",
      "product-led",
      "zero-to-one",
      "founder mode",
      "go-to-market",
      "disruptive",
      "operating system for",
      "10x",
      "wedge",
      "market pull",
    ],
  },
  enterprise: {
    id: "enterprise",
    label: "Enterprise",
    classification: "Enterprise LARP",
    guidance: "Overstate reliability, governance, transformation, and operational readiness.",
    vocabulary: [
      "enterprise-grade",
      "mission-critical",
      "scalable",
      "governance-ready",
      "compliance-ready",
      "production-ready",
      "single pane of glass",
      "end-to-end",
      "digital transformation",
      "control plane",
      "platform capability",
    ],
  },
  openSource: {
    id: "openSource",
    label: "Open Source",
    classification: "Open-Source LARP",
    guidance: "Use community, protocol, and maintainer language without pretending funding or adoption exists.",
    vocabulary: [
      "community-driven",
      "vendor-neutral",
      "open protocol",
      "open-weight",
      "forkable",
      "federated",
      "maintainer-led",
      "GitHub-native",
      "permissively licensed",
      "commons-aligned",
    ],
  },
  localAi: {
    id: "localAi",
    label: "Local AI",
    classification: "Local-AI LARP",
    guidance: "Celebrate local inference, sovereignty, edge devices, and no-cloud stubbornness.",
    vocabulary: [
      "locally inferenced",
      "self-hosted",
      "local-first",
      "sovereign",
      "edge-native",
      "on-device",
      "privacy-preserving",
      "no cloud dependency",
      "offline-capable",
      "local alignment",
    ],
  },
  homelab: {
    id: "homelab",
    label: "Homelab",
    classification: "Homelab LARP",
    guidance: "Treat home infrastructure like a sovereign datacenter with very personal SLAs.",
    vocabulary: [
      "Raspberry Pi",
      "bare metal",
      "rack-adjacent",
      "Proxmox-native",
      "self-hosted",
      "LAN-first",
      "home datacenter",
      "edge appliance",
      "NAS-backed",
      "sovereign ARM infrastructure",
    ],
  },
  consulting: {
    id: "consulting",
    label: "Consulting",
    classification: "Consulting LARP",
    guidance: "Convert simple actions into workstreams, stakeholder outcomes, and maturity journeys.",
    vocabulary: [
      "capability maturity",
      "transformation roadmap",
      "stakeholder alignment",
      "operating model",
      "value stream",
      "discovery phase",
      "north star metric",
      "enablement layer",
      "change management",
      "target state",
    ],
  },
  founderLinkedIn: {
    id: "founderLinkedIn",
    label: "Founder LinkedIn",
    classification: "Founder LARP",
    guidance: "Sound breathless, reflective, and a little too proud of a tiny operational improvement.",
    vocabulary: [
      "I was told this would not scale",
      "lessons learned",
      "founder mode",
      "build in public",
      "the future is local",
      "taste is the moat",
      "shipping velocity",
      "high agency",
      "distribution-first",
      "earned secret",
    ],
  },
  research: {
    id: "research",
    label: "Research",
    classification: "Research LARP",
    guidance: "Borrow academic caution and benchmark-adjacent phrasing without inventing results.",
    vocabulary: [
      "emergent behavior",
      "ablation",
      "benchmark-adjacent",
      "latent space",
      "evaluation harness",
      "methodological novelty",
      "reproducible",
      "artifact",
      "empirical signal",
      "capability frontier",
    ],
  },
  web3: {
    id: "web3",
    label: "Web3",
    classification: "Web3 LARP",
    guidance: "Add protocol, decentralization, and ownership language while avoiding fake token claims.",
    vocabulary: [
      "permissionless",
      "on-chain",
      "trust-minimized",
      "decentralized",
      "wallet-native",
      "protocol layer",
      "composable",
      "verifiable",
      "ownership graph",
      "coordination primitive",
    ],
  },
  appleSilicon: {
    id: "appleSilicon",
    label: "Apple Silicon",
    classification: "Local-AI LARP",
    guidance: "Treat consumer hardware as a sleek local inference accelerator with lifestyle implications.",
    vocabulary: [
      "Apple Silicon",
      "Neural Engine",
      "unified memory",
      "Metal-accelerated",
      "on-device",
      "battery-aware",
      "fanless compute",
      "desktop-class inference",
      "M-series",
      "thermal envelope",
    ],
  },
  archLinux: {
    id: "archLinux",
    label: "Arch Linux",
    classification: "Honourable Engineering LARP",
    guidance: "Lean into DIY purity, rolling releases, and the spiritual cost of maintaining your own machine.",
    vocabulary: [
      "btw",
      "pacman-native",
      "rolling-release",
      "userland",
      "AUR-adjacent",
      "composable desktop",
      "systemd-aligned",
      "dotfile-driven",
      "source-first",
      "minimal base system",
    ],
  },
  climateTech: {
    id: "climateTech",
    label: "Climate Tech",
    classification: "Climate Tech LARP",
    guidance: "Add sustainability language while avoiding fabricated environmental impact.",
    vocabulary: [
      "carbon-aware",
      "grid-responsive",
      "sustainability layer",
      "climate-positive",
      "low-energy",
      "resource-efficient",
      "green compute",
      "decarbonisation",
      "impact-aligned",
      "thermal externality",
    ],
  },
};

export const defaultCategories: CategoryId[] = ["ai", "corporate", "localAi", "homelab"];
export const allBuzzwords = categoryIds.flatMap((id) => categories[id].vocabulary);

export function getCategories(ids: readonly CategoryId[]) {
  return ids.map((id) => categories[id]);
}
